### ISSUE TITLE
hydrogen/halogen bond interaction angle torlerance enquiry

### ISSUE THREAD

**Issue by XiaochangLiu-UoE** [oddt/oddt#128]
Oddt versiton: 0.7

Dear developers,

Thank you for developing this amazing tool!

I am using the interaction module to detect hydrogen bonding and halogen interactions. 

There is a parameter  `tolerance` in both `oddt.interactions.hbonds()` and `oddt.interactions.halogenbonds()`. According to the instruction, the `base_angle/n_neighbors` would be bounded by this parameter. But in the implementation, there only seems to be the lower bound `(np.nan_to_num(angle1) > (base_angle / a_neighbors_num - tolerance)`. 

I am wondering would it be something like `(np.nan_to_num(angle1) > (base_angle / a_neighbors_num - tolerance)) & (np.nan_to_num(angle1) < (base_angle / a_neighbors_num + tolerance)`.  Or did I misunderstand the implementation? 

And also, could you please tell me why the base angle should be divided by the number of the neighbors? Because when the number of neighbors increases, there seems to be more 'true' hydrogen/halogen bond. If I misunderstand anything, please feel free to correct me. 

Thank you so much.

For your convenience, the complete implementation is followed.

`strict = (((np.nan_to_num(angle1) > (base_angle / a_neighbors_num - tolerance)) | np.isnan(angle1)) & ((np.nan_to_num(angle2) > (base_angle / d_neighbors_num - tolerance)) | np.isnan(angle2))).all(axis=-1)`

**Comment by mwojcikowski** [comment]
Hi @XiaochangLiu-UoE ,

It took me a while to understand my motivation, as this part of code is a bit legacy. The lack of upper bound is to form a funnel of strict bonds. Although my approach with scaling the base angle by the number of neighbors is probably not optimal, as it will lead to some false positive "strict" interactions. Well spotted.

Unfortunately doing that computation efficiently requires some tricks, but I will try to improve it. Also including upper bound limit might be valuable in that case. I'd try to establish the base angle using the hybridization instead of degree, which would be more appropriate.

**Comment by mwojcikowski** [comment]
Please check out the PR if the code there works as you'd expect. I think this is much better that previously, but still needs some validation.

Additionally NNscore baseline descriptors need to be validated. I wonder how this change will affect the NNscore performance.
