### ISSUE TITLE
Ring normal vector is calculated incorrectly in pip package

### ISSUE THREAD

**Issue by vtarasv** [oddt/oddt#158]
I believe the issue is that line 853 in oddt/toolkits/rdk `vector = np.cross(ring_vectors, np.roll(ring_vectors, 1)).mean(axis=0)`. Here argument axis=0 shouls be added explicitly. Otherwise it switches x, y, z coordinates.

**Comment by mwojcikowski** [comment]
Hi @vtarasv
This is a known issue that has been fixed already on the development version in #148. I'm in the process of addressing some of the issues that arise due to changes in ChEMBL APIs and unit tests on the repo and will make a new release to all the channels including pip. For the time being you can address this problem by installing oddt directly from github repo:

```
pip install git+https://github.com/oddt/oddt.git
