### ISSUE TITLE
ValueError: pdbqt is not a recognised RDKit format

### ISSUE THREAD

**Issue by Moleculomics** [oddt/oddt#29]
I just downloaded ODDT but it is not working.
Using the same script and files from the paper is raising the error:
ValueError: pdbqt is not a recognised RDKit format

How can I solve this?

**Comment by mwojcikowski** [comment]
Hi,
This is simple - RDKit does not support pdbqt files. The solution is simple, you should use OpenBabel instead.

If you wish to use RDKit you should convert pdbqt to PDB which is supported by RDKit. Unfortunately not all features are available with RDKit, such as Vina docking, due to limited support of file formats.

If it still does not work for you I will need some more information on which part/method of ODDT is failing for you.

**Comment by Moleculomics** [comment]
Hi,
Thank you for the reply.
One more question: how can I use openbabel instead of rdkit (using that same script)?

**Comment by mwojcikowski** [comment]
Actually if OpenBabel is installed it should be preferred over RDKit. Please verify if you have openbabel installed by:

> import pybel

If you fail to import Pybel then you have to properly install Openbabel to your environment.

On the ODDT part you can explicitly set the toolkit to one you desire at the top of your script, right after `import oddt`:

> oddt.toolkit = oddt.toolkits.ob 

OR

> oddt.toolkit = oddt.toolkits.rdk

**Comment by Moleculomics** [comment]
Hi,
That worked but I had to reinstall openbabel using conda.
Thank you!
