### ISSUE TITLE
oddt_cli gives "bad interpreter" error

### ISSUE THREAD

**Issue by samoturk** [oddt/oddt#45]
I installed oddt using pip and i get the following error when I try to run oddt_cli:
```bash
oddt_cli -h
bash: /home/samo/anaconda3/bin/oddt_cli: /home/travis/miniconda/envs/test-environment/bin/python: bad interpreter: No such file or directory
```
I guess the interpreter path is not adjusted when installing with pip and it keeps the travis' value.
I'm using anaconda python (python 3.6) distribution.

**Comment by mwojcikowski** [comment]
Nice find. This bug is present only in the wheel and egg distributions. The source package on pip has correct (unmodified) shebang. I've removed both from Pypi. Can you try to reinstall to verify if it works now? The conda channel `conda install -c mwojcikowski oddt` should be free from that bug. I need to dig around that issue to avoid it in future builds.

On next release I plan to introduce `conda install -c oddt oddt` for simplicity. This should happen some time this year, after we give PDBQT some testing.

**Comment by samoturk** [comment]
I can confirm that it works now. Thanks!
