### ISSUE TITLE
 use Residue.number instead of Residue.idx in all functions that detect interractions

### ISSUE THREAD

**Issue by fabricecarles** [oddt/oddt#85]
Hi,
This new isue follow the #71 
My problem is very simple: I wat that the following code return the original Residue.number value instead of Residue.idx. So for example I replace
`hydrophobic_contacts(prot, lig)[0]['resid']`
by
`hydrophobic_contacts(prot, lig)[0]['resnum']`
Result return an array because in 
`hydrophobic_contacts(prot, lig)[0].dtype`
There is both 
`('resid', '<i2'), ('resnum', '<i2')`
This is true for all functions that detect interactions except for pi_stacking.

`    # aromatic face to face (Column = 1), aromatic edge to face (Column = 2)
    rings, _, strict_parallel, strict_perpendicular = pi_stacking(
        protein, ligand)
    np.add.at(IFP, [np.searchsorted(
        resids, np.sort(rings[strict_parallel]['resnum'])[::-1]), 1], 1)
    np.add.at(IFP, [np.searchsorted(
        resids, np.sort(rings[strict_perpendicular]['resnum'])[::-1]), 2], 1)`

Note that in oddt version 0.5 the returned value is correct only with rdkit backend.
Now in oddt version 0.6 I dont know how to access  Residue.number for pi_stacking again.

**Comment by mwojcikowski** [comment]
Thanks for this detailed explanation - now I clearly see what is wrong. The `pi_stacking` returns `ring_dict` instead of `atom_dict` (which is intentional). During the switch from `resnum` to `resid` in RDKit we forgot to change the `ring_dict` structure to have both.

I will fix that issue (i.e. add `rings['resnum']`), but for now you can take advantage of `resid` to get `resnum`. `resid` is a 0-based index, thus you have to use it to subset `mol.res_dict`:
```python
rings, _, strict_parallel, strict_perpendicular = pi_stacking(protein, ligand)
mol.res_dict[rings['resid']]['resnum']
```

**Comment by fabricecarles** [comment]
Thanks ! 
Are you planning to deploy this update in your anaconda channel soon? 
Otherwise I will compile it ;)

Fabrice
