### ISSUE TITLE
documentation may need updating

### ISSUE THREAD

**Issue by Dgelemi** [oddt/oddt#87]
I don't know how much more work is going into the doc.
On the main landing page, there is an example with 
`mol.atom_dict[‘is_acceptor’]`
However it should be isacceptor

Another typo is
`protein_atoms, ligand_atoms, strict = hbond(protein, ligand)`
where it should be hbonds

I think I got some other errors when I tried some codes, but I can't remember them. 
One other think that could help is to explicitly show which module is used, for example, SimpleInteractionFingerprint in document could be oddt.fingerprints.SimpleInteractionFingerprint instead

**Comment by marta-sd** [comment]
Hi,
Thanks for reporting these problems and sorry for the confusion.

If you're willing to become ODDT contributor you can edit the [main page](https://github.com/oddt/oddt/blob/master/docs/index.rst) of the docs and create a pull request. Otherwise please let us know if you find any other errors and I will fix them.
